- .env.sample
- README.md
Expands the readme to include base instructions for building a spatalite image in which to run Tanzawa and instructions for running the development server. Also includes a few notes on how to customize Tanzawa.
> refs #72 Document how to get a local dev setup

- apps/indieweb/webmentions.py
Per the [webmention specs](https://www.w3.org/TR/webmention/#sender-notifies-receiver-p-3) when sending a webmention
> Any 2xx response code MUST be considered a success.
Tanzawa was only checking for 200. This PR updates our webmention sending logic to mark any response code in range of 200 - 299 as success.
This change allows us to audit / confirm webmention status easily from within the django admin again.
> refs #68 fix webmention record success flag

- apps/entry/views.py
- apps/feeds/views.py
Bookmark content for RSS feeds were broken. The root cause was a missing f before the string, so the content was not processed as an f-string.
This PR also fixes the feed title to use the site name, rather than hard-coded to "Tanzawa" and adds page titles when creating/editing a post.
> refs #87 Bookmarks RSS Feed Content Broken

- apps/feeds/views.py
- apps/public/views.py
- tests/test_feeds/test_feed.py
- tests/test_feeds/test_stream_feed.py
- tests/test_public/test_author_view.py
- tests/test_public/test_home_view.py
- tests/test_public/test_search_view.py
- tests/test_public/test_stream_view.py
Just as the title says. My parameterized unit tests for lists were the same as the permalink view. Unlisted posts should be accessible via the URL (if you know it) but they should not appear in any list publicly (even if you're logged in / it's your post)
> refs #35 prevent unlisted posts from appearing in streams :doh:

- apps/templates/entry/checkin/_form.html
With #35 the form id when editing posts was unified from the post type ( i.e. `note`, `article` etc..) to `entry`. I missed the checkin edit screen. This PR allows you to save checkins again.
> Fix saving checkins submit button

- apps/plugins/application/activation.py
- apps/plugins/views.py
This PR adds in a process to gracefully restart gunicorn/uWSGI servers after enabling or disabling a plugin. The reason this is necessary is because while modifying INSTALLED_APPS and clearing caches works in development, it only effects a single process. This is an issue when you have multiple processes as every process besides the one that handled the activation request is still operating as if the plugin has not been enabled. This will cause them to throw errors if you try to resolve plugin specific URLs as the routes do not exist for those processes.
> Gracefully Restart Web Server When Plugin Enabled / Disabled via Web

- apps/indieweb/forms.py
- apps/indieweb/serializers.py
- apps/indieweb/views.py
- tests/test_indieweb/test_indieauth.py
This commit brings the indieauth authorization api into line with the specs.
Authorization requests to indieauth can be made without a "scope" parameter.
In such a case we should not create a token record and not return any code value.
Addresses #160
> Indieauth no longer requires scope or me parameters

- apps/core/urls.py
- apps/core/views.py
- apps/templates/base_public.html
Adds a favicon view and caches the response for 1 day. Generates a svg of a site icon. Code from [Adam Johnson's](https://adamj.eu/tech/2022/01/18/how-to-add-a-favicon-to-your-django-site/) blog.
> Add favicon view

- apps/templates/base.html
- static/tailwind/style.css
This PR moves the new post links from a `<details>` tag inside the hamburger menu on mobile to nice big blocky buttons on the dashboard. This removes 2 taps when creating a new post.
Before:
After:
> Extract new post links from menu on mobile

- apps/indieweb/domain/indieauth/queries.py
- apps/indieweb/views.py
- tests/test_indieweb/test_indieauth.py
Updates the token response to include a `"me"` URL again, fixing login with tools like Quill.
> Fix indieauth token

- packer/base_server/README.md
- packer/base_server/base_server.pkr.hcl
- packer/base_server/setup/base_install.sh
- packer/base_server/setup/weekly_update.sh
- packer/base_server/templates/docker-compose.yml
- packer/base_server/templates/nginx.conf
- packer/base_server/templates/uwsgi_params
- packer/tanzawa/README.md
- packer/tanzawa/setup/base_install.sh
- packer/tanzawa/templates/env
- packer/tanzawa/templates/uwsgi.ini
- packer/tanzawa/uwsgi_tanzawa.pkr.hcl
This PR adds packer configurations that will allow us to:
* Build a server image that when started runs Tanzawa inside of a docker container
* Keeps the system relatively secure (auto-updates)
There's two main parts:
1. Packer script to setup the base server
2. Dockerfile for Tanzawa running in a production-ready state on uWSGI
Provisioning should be able to take the domain name that the server will run on to allow configuration of `certbot` and the django `ALLOWED_HOSTS` environment variables.
> Introduce packer

- apps/data/indieweb/apps.py
Accidentally stopped importing my handlers for when I receive a webmention which broke creation of the moderation record. This fixes that.
> Fix webmention signal

- front/tailwind.config.js
- static/tailwind/style.css
When layerizing, the streams component became deeper nested than the existing glob afforded. Add another glob to allow matching not just `forms.py`, but also `form` packages.
> Fix tailwind glob to find deeper nested forms

- apps/templates/trix/minimal_editor.html
Make it easy to make links when posting on the mobile first UI.
> Restore link button to quick post

- apps/templates/entry/note/_quick_form.html
Before all posts on mobile were always made published because there was a 'name' attribute on the publish button that shouldn't been there.
> Remove erroneous name attribute on publish button

- apps/core/settings.py
- docs/deployment/index.md
Includes instructions for how to setup nginx and Tanzawa running with uWSGI via Docker.
The "current" docker image at `jamesvandyne/tanzawa` is outdated / required that I run create `/var/run/tanzawa/` and chown that directory to `www-data` in order to run the uWSGI server.
TODO:
> Deployment docs

- apps/templates/public/trips/trip_detail.html
Makes the posts easier to read and the photos larger.
> Make trip blog posts wider

- apps/tanzawa_plugin/comment_by_email/plugin.py
For some reason a race condition started appearing when running tests in CI. Move the model import in the offending plugin to occur during TYPE_CHECKING only to avoid this.
> Fix Race condition on CI tests

- apps/domain/images/exif.py
Since upgrading the libraries, the exif dictionary now includes binary data and callables – not things we can serialize. Exclude those from our exif json blob.
> Stop trying to store private metadata

- .env.sample
- apps/application/entry/_open_graph.py
- apps/core/settings.py
- apps/domain/files/__init__.py
- apps/domain/files/_images.py
- apps/domain/files/queries.py
- apps/interfaces/public/home/views.py
- apps/templates/public/home.html
- static/tailwind/style.css
This PR adds a small gallery to the homepage so photos from recent checkins etc... are easily discoverable. It also:
* Sneaks in a a small refactor, moving an image query to a queries module
* Allows the highlighted stream to be configurable by the `HIGHLIGHT_STREAM_SLUG` in the django settings / environment variable / .env file. e.g. `HIGHLIGHT_STREAM_SLUG=the-week`.
> Add gallery to homepage

- apps/domain/files/queries.py
- apps/interfaces/dashboard/files/views.py
So I can insert pdf attachments after the original uploading.
> Return a fix size for non-image attachments

- apps/data/files/constants.py
- apps/domain/files/operations.py
- apps/domain/files/queries.py
- apps/domain/files/utils.py
- apps/domain/images/images.py
- apps/interfaces/dashboard/files/views.py
- apps/interfaces/public/files/views.py
- apps/templates/files/tfiles_browser.html
- requirements.lock
- requirements.txt
This PR allows Tanzawa to preview PDFs in the file browser. It refactors the image getting logic to better match our domain architecture. When attempting to fetch a PDF with format / size arguments, it will rasterize the first page as a png to allow it to convert to the target mime (webp).
It also improves how we detect file references in existing posts by using regex instead of (very) naive splitting of a url.
> Improve pdf upload handling

- .env.sample
- apps/core/settings.py
- apps/domain/sunbottle/client.py
- apps/domain/sunbottle/queries.py
- apps/interfaces/public/home/views.py
- apps/templates/public/home.html
- tests/test_public/test_home_view.py
This PR adds a small section on the homepage which shows some basic generation stats from Sunbottle.
> Add Generation from Sunbottle to the homepage

- apps/tanzawa_plugin/health/admin_urls.py
- apps/tanzawa_plugin/health/constants.py
- apps/tanzawa_plugin/health/forms.py
- apps/tanzawa_plugin/health/queries.py
- apps/tanzawa_plugin/health/templates/health/fragments/weight_graph.html
- apps/tanzawa_plugin/health/templates/health/health.html
- apps/tanzawa_plugin/health/views.py
- requirements.lock
- requirements.txt
- tests/tanzawa_plugins/health/test_queries.py
Before this PR the graph on the weight page was fixed to the last 10 records. Useful, but it could be better.
After this PR Tanzawa displays a select dropdown that allows users to toggle between 4 different durations:
* Six Weeks
* Month to date
* Last month
* All
https://github.com/jamesvandyne/tanzawa/assets/154726/66085b91-1255-4347-be07-6eb6e5452a60
> Health graph date filter

- apps/application/feeds/content.py
- apps/domain/files/queries.py
- requirements.lock
Before this PR:
* When fetching an image with a given format without a specified size, Tanzawa would return the first image in the format no matter the size. This resulted in Tanzawa returning thumbnail sized photos for images that were displayed much much larger.
* Each plugin that adjusted feed content would add a newline to the start of posts. This made weird spacing when reading posts in a feed reader.
After this PR:
* When fetching an image with just a target format specified, Tanzawa will return a picture of the same size in a different format.
* Tanzawa only adds newlines between feed content plugins if there's content returned by the plugin.
* Django upgraded to the latest version.
> Fix blurry photos on checkin

- apps/domain/files/queries.py
Getting the size of an image doesn't take the orientation into account. Ensure we can capture both horizontal and vertical photos.
Fixes PYTHON-DJANGO-B
> Find processed file by matching width or height

- apps/tanzawa_plugin/exercise/application/strava/_create_post_from_exercise.py
The primary photo value is None when there isn't a photo.
Fixes PYTHON-DJANGO-D
> Fix creating strava blog posts without photos

- apps/domain/files/operations.py
- apps/domain/images/images.py
When an image is over the "max" size served by Tanzawa publicly, Tanzawa automatically creates a resized version and saves it to disk.
The next time we request the image, if the original image is too large, Tanzawa should return resized image.
However, when querying for an existing resized image (so we do not have to perform the resize operation again), we only looked for the image's original size.
Change our logic to look for the original image, then the maximum resized image, then finally create a new processed file.
Fixes PYTHON-DJANGO-B
> Fetch resized image given just the mime

- apps/tanzawa_plugin/exercise/application/strava/_create_post_from_exercise.py
Start date local has a Z on it, which implies it's UTC, however it's actually localtime (as the name implies).
Using .to(timezone) results in the datetime being adjusted, and when you're ahead of GMT, means posts won't be accessible until UTC catches up with localtime. So for Japan this is 9 hours later.
Pass in the timezone directly so the resulting datetime is localtime with a timezone.
> Pass timezone to arrow when getting activity time

- apps/domain/indieweb/queries.py
- apps/interfaces/common/templatetags/indieweb.py
- apps/templates/indieweb/webmention/webmention.html
- apps/templates/public/fragments/webmention.html
- apps/templates/public/home.html
- apps/templates/public/post/post_detail.html
This PR cleans up the display of webmentions on the homepage, after they were hastily added.
> Webmention cleanup

- apps/interfaces/public/entry/views.py
Before this commit filtering bookmarks by tags with a space in them e.g. "climate change" would search for items tagged "climate" and "change".
After this commit we quote all tags that are passed in so in the example above we'd search for "climate change".
This also has the side benefit of allowing us to pass _multiple_ tags in and Tanzawa filters by both tags.
> Ensure bookmarks can filter multi-word tags

- apps/tanzawa_plugin/exercise/application/strava/_create_post_from_exercise.py
- apps/tanzawa_plugin/exercise/templates/exercise/exercise.html
Use correct timezone when creating posts from Strava
The field name "timezone" implies that it is just a timezone i.e. "Asia/Tokyo" or similar. However, they are in a format like "(GMT+9:00) Asia/Tokyo". Use just the "Asia/Tokyo" part when creating posts from Strava.
> Strava bits and bobs

- apps/application/entry/_post_to_bridgy.py
- apps/domain/files/operations.py
- apps/domain/gis/queries.py
- apps/domain/wordpress/extract.py
- apps/tanzawa_plugin/exercise/interfaces/dashboard/_strava.py
- requirements.lock
- tests/test_wordpress/test_extract.py
- tox.ini
This PR 
* Upgrades Django, DRF, and extruct to the latest point release.
* Removes pytz as a dependency
* Formats the codebase to the latest black standards
> Version bumps and reformatting

- apps/domain/sunbottle/client.py
Sunbottle generally returns json, but there are cases where it does not (e.g. 503 timeouts and the like).
Sunbottle information on the homepage is very much a "nice to have" and not critical so only attempt to process 200 OK responses.
> Stop attempting to json decode error responses from Sunbottle
