docs/customization.md, docs/deployment.md, docs/index.md, docs/sites-using-tanzawa.md, mkdocs.yml, requirements.lock, requirements_dev.txt
PR to install / configure mkdocs with some base documentation
=> refs #89 Add mkdocs

apps/public/views.py, apps/templates/public/trips/trip_detail.html, apps/templates/public/trips/ttrip_list.html
Adds page titles and cleans up trip page a bit
=> Cleanup Trips

apps/indieweb/views.py, apps/post/views.py, apps/public/views.py, apps/templates/indieweb/fragments/webmentions.html, apps/templates/indieweb/webmention/webmention.html, apps/templates/post/fragments/dashboard.html
* Convert webmention approval / disapproval to use a turbo-frame.
* Update webmention approval / disapproval view to link to the post
* Optimizes queries on public detail pages / admin dashboard
=> Webmention improvements

apps/templates/public/entry/checkin_item.html
Adds `u-checkin` marker as reported in #106
=> refs #106 fix checkin microformat

apps/templates/public/entry/checkin_item.html
=> refs #106 fix coordinates in u-checkin block

requirements.lock
Updates Django and Extruct to the latest versions.
=> Update Django and extruct

apps/indieweb/views.py
=> Remove the content-type in the data message to prevent reflected xss

apps/plugins/tanzawa_plugin/now/templates/now/navigation.html, apps/templates/base_public.html
This PR makes makes the hamburger menu use the selected theme's secondary color. It also fixes alignment issues in the navigation on mobile.
=> Hamburger Menu use Theme Color

README.md
So I started from your Dockerfile and modified it to work on the context of cloudron.io
which basically has its own base image and a few changes
- while doing so, I stumbled upon a bunch of issues that I will relate by opening issues 
- Loving it!
=> Added my Tanzawa :)

.env.sample, apps/core/settings.py, apps/entry/application/__init__.py, apps/entry/application/_open_graph.py, apps/entry/models.py, apps/files/domain/__init__.py, apps/files/domain/_images.py, apps/public/views.py, apps/templates/base_public.html, docs/customization.md, docs/index.md, requirements.lock, requirements.txt
Address issue #191 
Need to figure out the best way to handle `META_SITE_DOMAIN`, which is required, unless we use the django sites package.
=> Add open graph meta tag

apps/entry/forms.py, apps/entry/urls.py, apps/entry/views.py, apps/templates/base.html, apps/templates/entry/fragments/location_form.html, apps/templates/entry/fragments/syndication_form.html, apps/templates/entry/note/_quick_form.html, apps/templates/entry/note/quick.html, apps/templates/trix/editor.html, apps/templates/trix/minimal_editor.html, apps/trix/widgets.py, static/tailwind/style.css
Make it easier to post on the go.
=> Add mobile first status posting form

apps/application/feeds/content.py, apps/data/plugins/plugin.py, apps/data/plugins/pool.py, apps/interfaces/public/feeds/views.py, apps/tanzawa_plugin/comment_by_email/__init__.py, apps/tanzawa_plugin/comment_by_email/plugin.py, apps/tanzawa_plugin/comment_by_email/templates/comment_by_email/feed.html, docs/plugins/custom-plugins.md, tests/factories/entry.py, tests/factories/users.py, tests/tanzawa_plugins/comment_by_email/test_comment_by_email.py
This PR adds hooks to allow plugins to inject content before / after posts in RSS feeds and a basic plugin to invite readers to "Comment by email".
=> Add Reply by email plugin

apps/interfaces/dashboard/plugins/urls.py, apps/tanzawa_plugin/comment_by_email/plugin.py, apps/templates/plugins/fragments/plugin_list.html
Turns out `-` wasn't valid. :doh:
=> Fix url patterns when enabling/disabling plugins

.github/dependabot.yml, requirements.lock
Get the latest security goodies.
=> Upgrade django to 3.2.13

apps/application/feeds/content.py
=> Add newlines between content and plugin content in feeds

apps/core/settings.py
So the packer build process can start the Docker image
=> Set default values for all settings

apps/interfaces/public/feeds/views.py, docs/deployment/index.md, mkdocs.yml
=> Fix rss link

apps/tanzawa_plugin/health/admin.py, apps/tanzawa_plugin/health/forms.py, apps/tanzawa_plugin/health/models.py, apps/tanzawa_plugin/health/templates/health/health.html
Small quality if life improvements to health that I noticed after using it on mobile.
=> Health tweaks

apps/tanzawa_plugin/health/constants.py, apps/tanzawa_plugin/health/forms.py, apps/tanzawa_plugin/health/models.py, apps/tanzawa_plugin/health/templates/health/health.html, apps/tanzawa_plugin/health/views.py
A temporary health dashboard so we can view the last health measurement.
=> Health dashboard

apps/application/indieweb/webmentions.py
=> Handle invalid uuids when looking up posts for webmentions

apps/domain/posts/queries.py, apps/interfaces/public/home/views.py, apps/templates/base_public.html, apps/templates/public/fragments/meta_map.html, apps/templates/public/home.html, front/tailwind.config.js, static/tailwind/style.css
=> New homepage

packer/tanzawa/templates/uwsgi.ini, packer/tanzawa/uwsgi_tanzawa.pkr.hcl
Some attempts to get uWSGI playing nicely so I can deploy to Fly.io
=> Uwsgi jazz

.env.tox, .github/workflows/ci.yml, apps/application/entry/_open_graph.py, apps/core/settings.py, apps/data/plugins/pool.py, tests/tanzawa_plugins/conftest.py
So it doesn't just skip tests and mark the build as passing.
=> Update CI to use Python 3.11

apps/interfaces/public/files/forms.py, requirements.lock
This PR upgrades all the things.
=> Upgrade dependencies

apps/tanzawa_plugin/health/admin_urls.py, apps/tanzawa_plugin/health/templates/health/health.html, apps/tanzawa_plugin/health/views.py, apps/templates/base.html
Adds a quick and dirty graph for showing the last 10 measurements.
=> Add graph for showing weight over time

apps/interfaces/dashboard/entry/views.py, requirements.lock, tests/functional/interfaces/dashboard/entry/test_views.py
This PR fixes a bug where updating a published post also updates the published at date time to be the current time, rather than leaving it unchanged.
=> Fix update published at

apps/interfaces/public/files/views.py
=> Ensure we pass sizes as an integer when getting media

apps/domain/indieweb/webmention/__init__.py, apps/domain/indieweb/webmention/_queries.py, apps/interfaces/public/home/views.py, apps/templates/indieweb/webmention/webmention.html, apps/templates/public/home.html
So there's some sense of activity on the site, other than just my posts.
=> Add webmentions to homepage

apps/templates/public/entry/bookmark_item.html
Marked up with p-category tags so they'll share as hashtags.
=> Add tags to bookmark details page

apps/interfaces/public/files/urls.py, apps/interfaces/public/files/views.py, apps/templates/base_public.html, apps/templates/fragments/modal.html, apps/templates/public/files/modal.html, apps/templates/public/home.html, static/tailwind/style.css
=> Open clicks on gallery in a modal on homepage

apps/application/entry/__init__.py, apps/application/entry/_post_to_bridgy.py, apps/data/entry/constants.py, apps/domain/entry/queries.py, apps/interfaces/dashboard/entry/urls.py, apps/interfaces/dashboard/entry/views.py, apps/templates/interfaces/dashboard/entry/bridgy/_form.html
This PR makes it possible to syndicate posts to Bluesky via Bridgy.
Before sending
After sending
=> Add Bridgy Bluesky support

apps/tanzawa_plugin/exercise/application/strava/_create_post_from_exercise.py, apps/tanzawa_plugin/exercise/application/strava/_import_activities.py
This PR makes it so:
* Activities without gps tracking can be imported into Tanzawa
* You can create blog posts from activities without a description
=> Fix non run strava imports
